monolog:
    channels:
        - deprecation   # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - dev           # monolog.logger.dev


    handlers:
        deprecation:
            type:       rotating_file
            max_files:  3
            level:      debug
            channels:   [deprecation]
            path:       "%kernel.logs_dir%/%kernel.environment%.deprecation.log"

        dev:
            type:           fingers_crossed
            handler:        null_internal
            
when@dev:
    monolog:
        handlers:
            gs_command.dev_logger:
                type:           rotating_file
                max_files:      1
                path:           "%kernel.logs_dir%/gs_command_%kernel.environment%.log"
                level:          debug
                channels:       ["gs_command.dev_logger"]
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            
            dev:
                type:       rotating_file
                max_files:  3
                level:      debug
                channels:
                -   dev
            
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type:           fingers_crossed
                handler:        null_internal
